// <auto-generated />
using System;
using Flights.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Flights.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Flights.Data.Entities.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartureCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaneModel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b40df168-468c-4cbc-bc4e-7c42e9be41f9"),
                            ArrivalTime = new DateTime(2021, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = "Iasi",
                            DepartureTime = new DateTime(2021, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationCity = "Amsterdam",
                            PlaneModel = "B1"
                        },
                        new
                        {
                            Id = new Guid("07636c4e-c6e5-447f-a98f-42aa7cdc6af6"),
                            ArrivalTime = new DateTime(2021, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureCity = "Iasi",
                            DepartureTime = new DateTime(2021, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationCity = "Londra",
                            PlaneModel = "B6"
                        });
                });

            modelBuilder.Entity("Flights.Data.Entities.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2ea9dd2-629d-4138-9e71-a459a5032c83"),
                            FlightId = new Guid("b40df168-468c-4cbc-bc4e-7c42e9be41f9"),
                            User = "Popa Ion"
                        },
                        new
                        {
                            Id = new Guid("bdcedd4a-b5bb-4da4-8216-02db5060fb8d"),
                            FlightId = new Guid("b40df168-468c-4cbc-bc4e-7c42e9be41f9"),
                            User = "Rusu Lara"
                        },
                        new
                        {
                            Id = new Guid("a7d31ced-4866-458f-b718-932eef0d8802"),
                            FlightId = new Guid("07636c4e-c6e5-447f-a98f-42aa7cdc6af6"),
                            User = "Popescu Vasile"
                        },
                        new
                        {
                            Id = new Guid("71dbdf43-43a8-45bc-8337-456119bd64b5"),
                            FlightId = new Guid("07636c4e-c6e5-447f-a98f-42aa7cdc6af6"),
                            User = "Frunza Ioana"
                        });
                });

            modelBuilder.Entity("Flights.Data.Entities.Reservation", b =>
                {
                    b.HasOne("Flights.Data.Entities.Flight", null)
                        .WithMany("Reservations")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Flights.Data.Entities.Flight", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
